### ISSUE TITLE
.pkl files in Dataset 

### ISSUE THREAD

**Issue by usman221** [anonymous0121X/ST-SHN#2]
Hey @akaxlh / @anonymousHCCF can I have some idea which type of data is packed in these file

ST-SHN/Datasets/CHI_crime/trn.pkl
ST-SHN/Datasets/CHI_crime/tst.pkl
ST-SHN/Datasets/CHI_crime/val.pkl

Curious to know that because If i tried to run this code on any other dataset need to create those .pkl files first. Your comments will be very appreciated in this regards.

**Comment by akaxlh** [comment]
These are numpy ndarry compressed by the pickle module.
